version: '3.3'
services:
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 1337:80
    depends_on:
      - web

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/home/app/web/project/postgresql/data/
    env_file:
      - ./.env.prod.db


volumes:
  postgres_data:
  static_volume:
  media_volume:
